databases:
  - name: collection-db
    plan: free
    databaseName: collection_db

services:
  - type: web
    name: collection-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: collection-db
          property: connectionString
